import {
  colorGame,
  FlappyBird,
  MusicMania,
  Nodulus,
  numberMatch,
  BalloonPop,
  HoleInTheWall,
  WhiteBoard,
  WordChain,
  ScenarioSaga,
} from "@/public/images";

export const motorGames = [
  {
    title: "Music Mania",
    publisher: "Bandhu",
    rating: "4.8",
    players: "1828",
    views: "210",
    imageUrl: MusicMania,
    isHot: true,
    gameLink: "/music-mania",
  },
  {
    title: "Balloon Pop",
    publisher: "Bandhu",
    rating: "4.9",
    players: "1356",
    views: "6578",
    imageUrl: BalloonPop,
    isHot: true,
    gameLink: "/balloon-pop",
  },
  {
    title: "Hole in the Wall",
    publisher: "Bandhu",
    rating: "4.5",
    players: "2976",
    views: "4568",
    imageUrl: HoleInTheWall,
    isHot: true,
    gameLink: "/hole-in-the-wall",
  },
  {
    title: "Flappy Bird",
    publisher: "Bandhu",
    rating: "4.1",
    players: "644",
    views: "1232",
    imageUrl: FlappyBird,
    isHot: false,
    gameLink: "/flappy-bird",
  },
];

export const emotionalGames = [
  {
    title: "Color And Paint",
    publisher: "Bandhu",
    rating: "4.8",
    players: "1828",
    views: "250",
    imageUrl: colorGame,
    isHot: true,
    gameLink: "/color-paint",
  },
  {
    title: "Whiteboard",
    publisher: "Bandhu",
    rating: "4.7",
    players: "982",
    views: "424",
    imageUrl: WhiteBoard,
    isHot: true,
    gameLink: "/whiteboard",
  },
];

export const cognitiveGames = [
  {
    title: "Number Match - Memory Game",
    publisher: "Bandhu",
    rating: "4.8",
    players: "1828",
    views: "352",
    imageUrl: numberMatch,
    isHot: true,
    gameLink: "/number-match",
    favorite: true,
  },
  {
    title: "Nodulus",
    publisher: "Bandhu",
    rating: "4.8",
    players: "1928",
    views: "2738",
    imageUrl: Nodulus,
    isHot: false,
    gameLink: "/nodulus",
    favorite: false,
  },
  {
    title: "Word Chain",
    publisher: "Bandhu",
    rating: "4.6",
    players: "273",
    views: "2892",
    imageUrl: WordChain,
    isHot: false,
    gameLink: "/word-chain",
    favorite: false,
  },
];

export const socialGames = [
  {
    title: "Scenario Saga",
    publisher: "Bandhu",
    rating: "4.7",
    players: "982",
    views: "424",
    imageUrl: ScenarioSaga,
    isHot: true,
    gameLink: "/scenario-saga",
  },
];
