export const categoryValidation = {
    animals: [
        "dog",
        "cat",
        "rat",
        "pig",
        "cow",
        "bat",
        "hen",
        "ant",
        "bee",
        "tiger",
        "rabbit",
        "panda",
        "eagle",
        "snake",
        "horse",
        "sheep",
        "goat",
        "elephant",
        "penguin",
        "giraffe",
        "octopus",
        "kangaroo",
        "cheetah",
        "dolphin",
        "lion",
        "zebra",
        "rhino",
        "bear",
        "wolf",
        "fox",
        "deer",
        "moose",
        "camel",
        "llama",
        "koala",
        "monkey",
    ],
    countries: [
        "usa",
        "peru",
        "cuba",
        "chad",
        "iran",
        "mali",
        "fiji",
        "laos",
        "japan",
        "india",
        "spain",
        "kenya",
        "chile",
        "turkey",
        "mexico",
        "belgium",
        "thailand",
        "zimbabwe",
        "australia",
        "argentina",
        "singapore",
        "china",
        "russia",
        "brazil",
        "canada",
        "france",
        "germany",
        "italy",
        "egypt",
        "nigeria",
        "vietnam",
        "nepal",
        "iraq",
        "afghanistan",
        "albania",
        "algeria",
        "andorra",
        "angola",
        "antigua and barbuda",
        "armenia",
        "austria",
        "azerbaijan",
        "bahamas",
        "bahrain",
        "bangladesh",
        "barbados",
        "belarus",
        "belize",
        "benin",
        "bhutan",
        "bolivia",
        "bosnia and herzegovina",
        "botswana",
        "brunei",
        "bulgaria",
        "burkina faso",
        "burundi",
        "cabo verde",
        "cambodia",
        "cameroon",
        "central african republic",
        "comoros",
        "congo (brazzaville)",
        "congo (kinshasa)",
        "costa rica",
        "croatia",
        "cyprus",
        "czech republic",
        "denmark",
        "djibouti",
        "dominica",
        "dominican republic",
        "ecuador",
        "el salvador",
        "equatorial guinea",
        "eritrea",
        "estonia",
        "eswatini",
        "ethiopia",
        "gabon",
        "gambia",
        "georgia",
        "ghana",
        "greece",
        "grenada",
        "guatemala",
        "guinea",
        "guinea-bissau",
        "guyana",
        "haiti",
        "honduras",
        "hungary",
        "iceland",
        "indonesia",
        "ireland",
        "israel",
        "jamaica",
        "jordan",
        "kazakhstan",
        "kiribati",
        "north korea",
        "south korea",
        "kosovo",
        "kuwait",
        "kyrgyzstan",
        "latvia",
        "lebanon",
        "lesotho",
        "liberia",
        "libya",
        "liechtenstein",
        "lithuania",
        "luxembourg",
        "madagascar",
        "malawi",
        "malaysia",
        "maldives",
        "malta",
        "marshall islands",
        "mauritania",
        "mauritius",
        "micronesia",
        "moldova",
        "monaco",
        "mongolia",
        "montenegro",
        "morocco",
        "mozambique",
        "myanmar",
        "namibia",
        "nauru",
        "netherlands",
        "new zealand",
        "nicaragua",
        "niger",
        "north macedonia",
        "norway",
        "oman",
        "pakistan",
        "palau",
        "panama",
        "papua new guinea",
        "paraguay",
        "philippines",
        "poland",
        "portugal",
        "qatar",
        "romania",
        "rwanda",
        "saint kitts and nevis",
        "saint lucia",
        "saint vincent and the grenadines",
        "samoa",
        "san marino",
        "sao tome and principe",
        "saudi arabia",
        "senegal",
        "serbia",
        "seychelles",
        "sierra leone",
        "slovakia",
        "slovenia",
        "solomon islands",
        "somalia",
        "south africa",
        "south sudan",
        "sri lanka",
        "sudan",
        "suriname",
        "sweden",
        "switzerland",
        "syria",
        "taiwan",
        "tajikistan",
        "tanzania",
        "timor-leste",
        "togo",
        "tonga",
        "trinidad and tobago",
        "tunisia",
        "turkmenistan",
        "tuvalu",
        "uganda",
        "ukraine",
        "united arab emirates",
        "united kingdom",
        "uruguay",
        "uzbekistan",
        "vanuatu",
        "vatican city",
        "venezuela",
        "yemen",
        "zambia",
    ],
    fruits: [
        "fig",
        "pear",
        "lime",
        "plum",
        "date",
        "kiwi",
        "apple",
        "mango",
        "grape",
        "peach",
        "lemon",
        "orange",
        "banana",
        "dragonfruit",
        "pineapple",
        "pomegranate",
        "blackberry",
        "raspberry",
        "strawberry",
        "blueberry",
        "watermelon",
        "papaya",
        "guava",
        "coconut",
        "apricot",
        "cherry",
        "cranberry",
        "grapefruit",
        "tangerine",
        "nectarine",
    ],
};